### ISSUE TITLE
11月8日版本更多设置保存提示数据库有问题

### ISSUE THREAD

**Issue by hecarli555** [taksssss/EPG-Server#24]
![image](https://github.com/user-attachments/assets/eb8023d3-84ae-46bd-a5b9-2e7c8dc0d356)
如图，更多设置保存后再点进去看，设置又还原了。。。。

**Comment by taksssss** [comment]
你是用MySQL么？我这边两种都测试过，貌似都没问题。

**Comment by hecarli555** [comment]
> 你是用MySQL么？我这边两种都测试过，貌似都没问题。

数据库那个我是用的默认的，没动过设置，就刚刚更新容器后尝试改个更多设置里补充公告否保存就提示这个了，然后我切换另一个数据库再保存还是出现连接失败的提示。。。。

**Comment by taksssss** [comment]
提示完这个之后，能正常进入管理界面么？我这边没找到复现的途径。

**Comment by hecarli555** [comment]
> 提示完这个之后，能正常进入管理界面么？我这边没找到复现的途径。

![image](https://github.com/user-attachments/assets/71f17728-b28a-4c09-bc52-f8f5cb7e7197)
更新完容器后进入更多设置显示是这样的，感觉是有问题

**Comment by taksssss** [comment]
应该浏览器缓存导致的。
算了，我还是版本回滚，去掉在线升级功能吧，感觉这个功能问题多多。

**Comment by nange01** [comment]
版本确实有问题，源链接访问404错误，显示未生成xmltv文件，之前版本都没有这个问题

**Comment by hecarli555** [comment]
> 应该浏览器缓存导致的，下个版本解决。 感觉在线升级功能问题多多，还是做回滚算了。

回滚后目前正常了

**Comment by nange01** [comment]
> > 应该浏览器缓存导致的，下个版本解决。 感觉在线升级功能问题多多，还是做回滚算了。
> 
> 回滚后目前正常了

一切正常了👍

**Comment by taksssss** [comment]
> > 应该浏览器缓存导致的，下个版本解决。 感觉在线升级功能问题多多，还是做回滚算了。
> 
> 回滚后目前正常了

上个版本js部分逻辑改了，浏览器缓存了旧版本，导致出现各种奇奇怪怪的问题。
