### ISSUE TITLE
新功能-有空可以搞搞

### ISSUE THREAD

**Issue by YanG-1989** [taksssss/EPG-Server#25]
🤓什么时候，搞个epg英语转中文。（多语言）
但是没什么用，没事做的时候可以考虑加上去。
节目名称不需要..单独转节目表就行了🤪

**Comment by taksssss** [comment]
如果调用接口的话，给用户的配置又不友好。
本地跑的话，会比较吃力吧？

**Comment by YanG-1989** [comment]
不知道..
你现在不是有一个繁体转简体吗？
应该还好吧..

**Comment by taksssss** [comment]
那差别很大啊，繁体转简体都是汉字，一对一转换就行了。
英文到中文是翻译了😂

**Comment by YanG-1989** [comment]
> 那差别很大啊，繁体转简体都是汉字，一对一转换就行了。
> 英文到中文是翻译了😂

🤪 我还以为差不多....
