### ISSUE TITLE
关于功能名词解释

### ISSUE THREAD

**Issue by hecarli555** [taksssss/EPG-Server#26]
大佬可否考虑一些人性化的提示更改，就是各个功能能否加上一个功能说明或者解释，数据保存时间和缓存时间这个有点区分不了（只保存前后2天的epg应该是对应哪个设置？），可以像补充预告那样加入指针提示，简单介绍一下该功能作用或名词解释，这样更方便大家理解使用

**Comment by taksssss** [comment]
只能选清除几天前的数据。
缓存那个已经在更多里面了，不清楚的话直接用默认关闭的即可。
我写个memcache的话，也还是看不懂，那个用来减少数据库访问而已，个人用的话，也没啥区别。

**Comment by taksssss** [comment]
你这个数据保存时间选2就行了，超过2天前的数据都会自动清除。未来的数据不会限制天数。
