### ISSUE TITLE
数据库是动了么。。。。更新今天的新版后配置没有了。。。。

### ISSUE THREAD

**Issue by hecarli555** [taksssss/EPG-Server#27]
数据库是动了么。。。。更新今天的新版后配置没有了。。。。

**Comment by taksssss** [comment]
路径映射从 `./data:/htdocs/epg/data` 修改为 `./data:/htdocs/data`

**Comment by hecarli555** [comment]
> 路径映射从 `./data:/htdocs/epg/data` 修改为 `./data:/htdocs/data`

建议这个也写到更新日志里。。。。
