### ISSUE TITLE
24.11.13版本有问题

### ISSUE THREAD

**Issue by SherwinWg** [taksssss/EPG-Server#28]
管理页面不显示，报错
Not Found
The requested URL was not found on this server.

Apache/2.4.62 (Unix) Server at 192.168.2.12 Port 8877

退回24.11.12版本就好了。

**Comment by SherwinWg** [comment]
路径映射从 ./data:/htdocs/epg/data 修改为 ./data:/htdocs/data
改了这个映射还是一样不行。

**Comment by taksssss** [comment]
访问地址也变了，这个版本开始，将epg去掉了，直接 :5678/manage.php

**Comment by taksssss** [comment]
下个版本会兼容之前的访问路径。

**Comment by hecarli555** [comment]
> 新版本支持旧地址重定向回新地址了，有空试试。

这已改路径真的是大麻烦。。。。图标，epg全都失效了，又得重新整理
