### ISSUE TITLE
生成m3u和txt地址有

### ISSUE THREAD

**Issue by SherwinWg** [taksssss/EPG-Server#29]
配置文件地址以https开通，生成的地址却以http开头

**Comment by taksssss** [comment]
更新了一个版本，你试试行不行，我这边没 ssl 证书，没办法测试。

**Comment by SherwinWg** [comment]
> 更新了一个版本，你试试行不行，我这边没 ssl 证书，没办法测试。

我用的反代，现在可以了，辛苦大佬。
