### ISSUE TITLE
无鼠标操作环境望优化

### ISSUE THREAD

**Issue by nange01** [taksssss/EPG-Server#30]
新版本对移动设备操作有点不友好，弹窗提示在pc端可以鼠标点击任意地方关闭，但是在移动设备上只能通过大刷新来关闭，safari浏览器，望优化一下
![FB009410-53AB-4AAA-BF77-87407514B5EC](https://github.com/user-attachments/assets/d6a48c61-8478-467a-ba7f-bbdcdaba4938)

**Comment by taksssss** [comment]
啊这。。。Safari还会不支持这种函数的么。
安卓平台的浏览器一切正常。
回头看看怎么回事吧。

**Comment by taksssss** [comment]
你用内置的文件管理器修改 `assets/js/manage.js` ，将两个
```
window.onclick = function(event) {
```
改成
```
window.addEventListener("click", function(event) {
```
再用无痕模式打开，看看能不能生效。

**Comment by hecarli555** [comment]
> 你用内置的文件管理器修改 `assets/js/manage.js` ，将两个
> 
> ```
> window.onclick = function(event) {
> ```
> 
> 改成
> 
> ```
> window.addEventListener("click", function(event) {
> ```
> 
> 再用无痕模式打开，看看能不能生效。

![image](https://github.com/user-attachments/assets/f25ddfee-65be-46fa-ac81-d2785a747b64)
借贴反应一个小小的问题，最底下这个排版感觉左右结构比上下结构要好看舒服

**Comment by taksssss** [comment]
> 新版本对移动设备操作有点不友好，弹窗提示在pc端可以鼠标点击任意地方关闭，但是在移动设备上只能通过大刷新来关闭，safari浏览器，望优化一下 ![FB009410-53AB-4AAA-BF77-87407514B5EC](https://private-user-images.githubusercontent.com/178385403/389362462-d6a48c61-8478-467a-ba7f-bbdcdaba4938.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTMzNTUsIm5iZiI6MTczMjU5MzA1NSwicGF0aCI6Ii8xNzgzODU0MDMvMzg5MzYyNDYyLWQ2YTQ4YzYxLTg0NzgtNDY3YS1iYTdmLWJiZGNkYWJhNDkzOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDM1MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI5ZTZlNjAxZDgzOGE0ODk0Y2FlNzEzNTg5MTYyZDU5YzJjM2EyYzdiNGJmOGRkNDNmZDU2MmQwMzZlZGVjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.egLYxXnQyMJSyc3SmrSrMlRFEqvOYMTMoYOgINA-8jE)

算了，下个版本把关闭按钮都加上去了。

**Comment by taksssss** [comment]
> > 你用内置的文件管理器修改 `assets/js/manage.js` ，将两个
> > ```
> > window.onclick = function(event) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成
> > ```
> > window.addEventListener("click", function(event) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再用无痕模式打开，看看能不能生效。
> 
> ![image](https://private-user-images.githubusercontent.com/76683744/389497856-64757a3e-b8fa-48f1-845d-5bd4ababea8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1OTMzNTUsIm5iZiI6MTczMjU5MzA1NSwicGF0aCI6Ii83NjY4Mzc0NC8zODk0OTc4NTYtNjQ3NTdhM2UtYjhmYS00OGYxLTg0NWQtNWJkNGFiYWJlYThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAzNTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGFkNmVkYzNmMzYzODA5YTlkMzc1OTIzYzhlNDlmYzE0ODA4ZWUzZDM5MjA4MTY0ODI0YmRhZjhkNWEwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6df1DCfKW8lRuWPdCMRUWFmLnpXUxXzOwDmr9y-0AQ0) 借贴反应一个小小的问题，最底下这个排版感觉左右结构比上下结构要好看舒服

嗯嗯，这里也会优化。

**Comment by nange01** [comment]
> 你用内置的文件管理器修改`assets/js/manage.js`，将两个
> 
> ```
> window.onclick = function(event) {
> ```
> 
> 改为
> 
> ```
> window.addEventListener("click", function(event) {
> ```
> 
> 再用无痕模式打开，看看能不能生效。

有点尴尬，我部署在软路由上的，docker容器下估计是缺少插件，看不到容器文件没法修改😅

**Comment by taksssss** [comment]
> > 你用内置的文件管理器修改`assets/js/manage.js`，将两个
> > 
> > ```
> > window.onclick = function(event) {
> > ```
> > 
> > 改为
> > 
> > ```
> > window.addEventListener("click", function(event) {
> > ```
> > 
> > 再用无痕模式打开，看看能不能生效。
> 
> 有点尴尬，我部署在软路由上的，docker容器下估计是缺少插件，看不到容器文件没法修改😅

我说的是管理页面内置的 文件管理器 tinyfilemanager 😂
新版本会有关闭按钮了，不过还是想看看点击关闭是不是这里导致异常。
除了状态框，其他页面能正常点击空白区域关闭么？还是只能点关闭按钮？

**Comment by nange01** [comment]
已修改保存并重启了docker容器，无痕模式重新打开页面，除了“更新数据”“管理数据”“管理文件”三个按钮有反应，其它均无任何反应。另“保存配置”点击后出现如下页面
![9C2904F1-5A63-4B27-83E6-557F2A0D1A8A](https://github.com/user-attachments/assets/c55146d0-39be-4a05-bd81-13cc83cdea1a)

**Comment by taksssss** [comment]
> 已修改保存并重启了docker容器，无痕模式重新打开页面，除了“更新数据”“管理数据”“管理文件”三个按钮有反应，其它均无任何反应。另“保存配置”点击后出现如下页面 ![9C2904F1-5A63-4B27-83E6-557F2A0D1A8A](https://private-user-images.githubusercontent.com/178385403/390314561-c55146d0-39be-4a05-bd81-13cc83cdea1a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjEyNjEsIm5iZiI6MTczMjcyMDk2MSwicGF0aCI6Ii8xNzgzODU0MDMvMzkwMzE0NTYxLWM1NTE0NmQwLTM5YmUtNGEwNS1iZDgxLTEzY2M4M2NkZWExYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTUyMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U3YmY3ZDM1ZWJjMmRkZWM4OTA3ZDI0ZTFjMjA2MDc5YTZkZWY3MTRlODg5ZTA3MWQxZmYwZjI5NGI2ODYwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uKM1NXbGI4vQkJRINmXwQ0YctfXutseK5b3FXqQbv7E)

那算了，别管它了，我已经加上关闭按钮了。下个版本再试试。

**Comment by hecarli555** [comment]
> > 已修改保存并重启了docker容器，无痕模式重新打开页面，除了“更新数据”“管理数据”“管理文件”三个按钮有反应，其它均无任何反应。另“保存配置”点击后出现如下页面 ![9C2904F1-5A63-4B27-83E6-557F2A0D1A8A](https://private-user-images.githubusercontent.com/178385403/390314561-c55146d0-39be-4a05-bd81-13cc83cdea1a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjEyNjEsIm5iZiI6MTczMjcyMDk2MSwicGF0aCI6Ii8xNzgzODU0MDMvMzkwMzE0NTYxLWM1NTE0NmQwLTM5YmUtNGEwNS1iZDgxLTEzY2M4M2NkZWExYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTUyMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U3YmY3ZDM1ZWJjMmRkZWM4OTA3ZDI0ZTFjMjA2MDc5YTZkZWY3MTRlODg5ZTA3MWQxZmYwZjI5NGI2ODYwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uKM1NXbGI4vQkJRINmXwQ0YctfXutseK5b3FXqQbv7E)
> 
> 那算了，别管它了，我已经加上关闭按钮了。下个版本再试试。

来催更了大佬

**Comment by taksssss** [comment]
> > > 已修改保存并重启了docker容器，无痕模式重新打开页面，除了“更新数据”“管理数据”“管理文件”三个按钮有反应，其它均无任何反应。另“保存配置”点击后出现如下页面 ![9C2904F1-5A63-4B27-83E6-557F2A0D1A8A](https://private-user-images.githubusercontent.com/178385403/390314561-c55146d0-39be-4a05-bd81-13cc83cdea1a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjEyNjEsIm5iZiI6MTczMjcyMDk2MSwicGF0aCI6Ii8xNzgzODU0MDMvMzkwMzE0NTYxLWM1NTE0NmQwLTM5YmUtNGEwNS1iZDgxLTEzY2M4M2NkZWExYS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTUyMjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U3YmY3ZDM1ZWJjMmRkZWM4OTA3ZDI0ZTFjMjA2MDc5YTZkZWY3MTRlODg5ZTA3MWQxZmYwZjI5NGI2ODYwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uKM1NXbGI4vQkJRINmXwQ0YctfXutseK5b3FXqQbv7E)
> > 
> > 
> > 那算了，别管它了，我已经加上关闭按钮了。下个版本再试试。
> 
> 来催更了大佬

还有个功能在改，改完再一起发吧。

**Comment by nange01** [comment]
新版本已安装，问题得到有效解决

**Comment by nange01** [comment]
IOS端Safari点关闭才有效，PC端点关闭和空白处都生效

**Comment by taksssss** [comment]
好的，暂时就这样吧。不清楚哪个接口iOS端不支持……
