### ISSUE TITLE
请教猫接口下载失败问题

### ISSUE THREAD

**Issue by youngking525** [taksssss/EPG-Server#31]
![1](https://github.com/user-attachments/assets/da524c0d-bb9d-46d1-8ca4-263557a7733d)
![2](https://github.com/user-attachments/assets/6e0943c4-ba70-4194-9950-37e111570678)
是写法错误还是网络问题呢？求教

**Comment by taksssss** [comment]
奇怪，你这几个我试了一下，都是可以的……感觉像是网络问题。
