### ISSUE TITLE
有个想法不知道能不能实现

### ISSUE THREAD

**Issue by hecarli555** [taksssss/EPG-Server#32]
就是抓取一个epg源的时候，我只想抓取它里面指定频道的信息，其它频道不抓取，这个功能能实现么？（1是想省点流量2是抓一大堆没用的频道信息tivimate这些客户端回卡死）

**Comment by taksssss** [comment]
这个后面可以加，大概长这个样子吧。
`CCTV1, CCTV2, CCTV3 => http://xxx.com/xxx.xml.gz`

**Comment by taksssss** [comment]
更新了，有空试试。

**Comment by hecarli555** [comment]
> 更新了，有空试试。

小白有个问题，就是遍历整个epg源是否等同于把整个epg信息都下载下来呢？我原本的想法是先遍历epg源里的频道，然后再下载指定频道的信息（主要就是想省点流量。。。）

**Comment by taksssss** [comment]
> > 更新了，有空试试。
> 
> 小白有个问题，就是遍历整个epg源是否等同于把整个epg信息都下载下来呢？我原本的想法是先遍历epg源里的频道，然后再下载指定频道的信息（主要就是想省点流量。。。）

不管你更新什么数据，都是要把源文件下载再解析的，你在乎流量的话就用.xml.gz的，文件大小只有xml的1/10左右。
