### ISSUE TITLE
直播源管理 相关建议

### ISSUE THREAD

**Issue by nange01** [taksssss/EPG-Server#33]
1.在“直播源管理”里面，订阅源解析修改并打开同步功能后，建议只同步直播地址。其它已修改的不做任何变动，这样既能获得及时的更新，自己修改的又能一直生效。如果订阅源同步后有新增的频道可以归类到自动生成的新分组里，如果订阅源同步后有删减的频道同步后直播地址一栏就为空了，也能及时发现和管理
2.在“直播源管理”里面，可以在解析后的频道前后添加“显示/隐藏”功能，这样不想要的频道即使同步后也能不会出现在生成的源里面

纯个人建议，如有异想天开还请海涵

**Comment by taksssss** [comment]
回头再看看添加一个字段标记唯一源吧。
有初步想法，应该是能做的。

**Comment by nange01** [comment]
可以添加新字段“源频道名”，现有的“频道名”改成“重命名”，这样源频道名可以作为唯一标记

**Comment by nange01** [comment]
个人觉得方案1比较合适，地址变更就代表之前的地址不能用了，没必要恢复

另外，针对同名不同直播地址暂且叫多线路频道吧，多线路频道可以通过不同类型文件来解决，比如生成的m3u文件多线路频道默认只保留第一个，生成的txt文件包含所有多线路频道

**Comment by nange01** [comment]
也可以添加新字段“线路备注”，默认添加“线路1、线路2、线路3……”，这样可以结合频道名和线路备注就能成为唯一标注

**Comment by taksssss** [comment]
> 也可以添加新字段“线路备注”，默认备注添加“线路1、线路2、线路3……”，这样可以结合频道名和线路备注就能成为唯一标注

加线路备注能成为唯一标注，但是问题是地址更变，没办法确认线路对不对得上，也还是回到前面那个问题上。
我本来也是打算用方案1了，来源+分组+频道名+直播地址，更变的话就当新线路处理，不恢复。下下个版本推送吧。

**Comment by nange01** [comment]
对，你这个逻辑相对来说更稳妥一些，期待你的成果

**Comment by taksssss** [comment]
更新版本了，有空试试吧。
