### ISSUE TITLE
大佬，请教下epgshare源因数据库太大无法解析的问题。

### ISSUE THREAD

**Issue by philboycn** [taksssss/EPG-Server#34]
源：https://epgshare01.online/epgshare01/epg_ripper_US_LOCALS2.xml.gz

无法下载和解析。看了下里面有50多万条数据，可能网页已经停止转动了还没解析好。

**Comment by taksssss** [comment]
好家伙，压缩后还30多M，这解压后不得300M了。。。我回头看看吧

**Comment by philboycn** [comment]
> 好家伙，压缩后还30多M，这解压后不得300M了。。。我回头看看吧

^-^谢大佬！

**Comment by taksssss** [comment]
应该是内存不够，默认设置512M。
你在 `docker run` 的时候加上 `-e PHP_MEMORY_LIMIT=2048MB`。

**Comment by philboycn** [comment]
> 应该是内存不够，默认设置512M。 你在 `docker run` 的时候加上 `-e PHP_MEMORY_LIMIT=2048MB`。

设置了，也升级到最新版本了，还是不行呀老大？要不设置里加一个内存限制设置？

**Comment by taksssss** [comment]
这种运行环境相关的设置，不会加到应用里面。
我试过是可以的， `docker run -d -e PHP_MEMORY_LIMIT=2G --name php-epg -p 5678:80 --restart always taksss/php-epg:latest` ，类似于这样。

**Comment by philboycn** [comment]
可以了大佬，谢谢！原来是要=2G，=2048MB是不行的，哈哈。感谢大佬的epgserver！我使用Threadfin，这个程序不能很地解析比较大的xml，有了epgserver中转，很多问题都解决了，谢谢大佬！
