### ISSUE TITLE
直播源管理 相关功能咨询

### ISSUE THREAD

**Issue by nange01** [taksssss/EPG-Server#35]
大佬，请问最新版的“直播源管理”里面的解析后最后一栏的“保持”，具体是保持同步更新还是保持当前修改不同步更新呢？

**Comment by taksssss** [comment]
保存后有提示的，就是重新解析，编辑过的内容会维持。
感觉这个选项不好描述😂

**Comment by nange01** [comment]
意思是修改的内容比如“台标链接、分组”等会保持不变，没有修改的内容比如“直播地址”会同步更新是吗？
另外目前是根据什么来确定唯一标识的？是“频道名”吗？频道重命名是否会考虑加入呢？

**Comment by taksssss** [comment]
唯一标识是 来源URL+分组+频道名+直播地址 。
直播地址变了的话，没办法同步的。

**Comment by nange01** [comment]
明白了，多谢
