### ISSUE TITLE
关于使用直播源管理问题

### ISSUE THREAD

**Issue by linzbc** [taksssss/EPG-Server#36]
问题：当上传比较多的直播源时就会出现‘解析过程中发生错误：SyntaxError: Unexpected end of JSON input’等问题。
过程测试:远程或者本地，单个列表时不会出现上诉提示，证明不是上传列表有问题。当放4-5个列表时有间歇性的出现。数量再多一个时就直接出现上面提示。每个列表几百个频道有的可能上千个频道。
目前情况是所有版本都会有这个问题。是否有频道数量限制？

**Comment by taksssss** [comment]
没限制的。我这边加起来2500个频道，没遇到过。有更详细的报错信息吗？报错行号啥的。

**Comment by taksssss** [comment]
找到原因了，默认限制30秒，超过就报超时。我下个版本改一下吧。

**Comment by linzbc** [comment]
> 没限制的。我这边加起来2500个频道，没遇到过。有更详细的报错信息吗？报错行号啥的。
![360截图20241209174729085](https://github.com/user-attachments/assets/edbc3cca-a33a-4e90-859e-946876fb1015)
我得频道比你多，我有的订阅单个就1500多个这些总量超过3000以上

**Comment by linzbc** [comment]
> 找到原因了，默认限制30秒，超过就报超时。我下个版本改一下吧。

哈哈。好的，我的单个订阅都超过1500左右
![QQ20241209-175108](https://github.com/user-attachments/assets/8f24e8df-f689-430e-b2a7-a64dda3e7334)

**Comment by taksssss** [comment]
新版本修复了，有空试试吧。
