### ISSUE TITLE
直播源管理 相关建议

### ISSUE THREAD

**Issue by nange01** [taksssss/EPG-Server#37]
我又来提建议了……

直播源管理可以添加自定义dome 模板，差不多也就分组和频道名两项，台标和epg都用本项目的，根据填写的订阅源来匹配自定义的频道，如果匹配到多个直播地址，就根据订阅源顺序来排序。填写的订阅源默认命名123456……也可自定义，然后添加一个“直播源备注”的开关，开启这个功能就在输出的订阅源的直播地址后面用“$”连接填写的订阅源的定义，比如添加的订阅源自为
凡明明；https://vanmingming.vom/iptv.m3u
输出的订阅源的直播地址就：http://123.123.vom/ccav1.m3u8$凡明明

因为这个备注功能目前有的播放器不识别，所以用开关按钮来根据需要选择

**Comment by taksssss** [comment]
后面再看看吧。
应该还是能实现的。
格式类似于txt：
#分组1
频道1
频道2
#分组2
频道3
频道4

**Comment by nange01** [comment]
那就有劳大佬了，等您好消息

**Comment by taksssss** [comment]
加进去了，备注用的是 自定义分组前缀+原分组名 。
感觉还挺方便的，至少不会乱糟糟了。

**Comment by nange01** [comment]
挺好用的，只是匹配似乎有点小问题，这里的cctv16、cctv4k和cctv8K频道匹配出现错误，cctv4K和8K匹配不到，cctv16出现匹配错误，200+的频道使用tivimate拉取列表出现了1000+多个，另外直播地址备注功能部分播放器不支持，还需要添加开关按钮
<img width="399" alt="屏幕截图 2024-12-14 132157" src="https://github.com/user-attachments/assets/6b678a07-511c-4932-95e2-48bac7872053" />

**Comment by taksssss** [comment]
你这用法不太对吧？
既然是模板了，为啥还要出现重复的频道？
cctv16、cctv164k_10、cctv-16-4k-hevc、cctv16-4k-sdr这几个频道，在处理后都会当成cctv16，然后每一个都会匹配所有频道，就一大堆了。
你现在要做的是聚合，所以你只需要保留 cctv16 或者 cctv16奥林匹克 一个就可以了啊，它会匹配所有符合的源。
开关按钮这个，下个版本可以加个 `$关闭备注` 来标记。

**Comment by taksssss** [comment]
我发现我们想的不是一个东西，我做的是模糊匹配，定义模板后可以将所有符合的频道都整理在一起。
你想的是精准匹配，只是对源做重排序。

**Comment by nange01** [comment]
是模糊匹配没错，我截图三张只显示了一张，没表述清楚，我有尝试模板填写图片这样，也有直接填写cctv16,cctv4K,cctv8k，但是4K 和8K的匹配不到，16的没问题

**Comment by taksssss** [comment]
试了一下，确实有点小问题，cctv4k能匹配，大写的cctv4K就匹配不了，应该是替换函数匹配到映射规则之后没有统一转成大写，回头改一下。

**Comment by taksssss** [comment]
```php
// 获取处理后的频道名：$t2s参数表示繁简转换，默认false
function cleanChannelName($channel, $t2s = false) {
    global $Config;
    $channel_ori = $channel;
    
    // 默认忽略 - 跟 空格
    $channel_replacements = ['-', ' '];
    $channel = str_replace($channel_replacements, '', $channel);

    // 频道映射，优先级最高，支持正则表达式和多对一映射
    foreach ($Config['channel_mappings'] as $replace => $search) {
        if (strpos($search, 'regex:') === 0) {
            $pattern = substr($search, 6);
            if (preg_match($pattern, $channel_ori)) {
                return strtoupper(preg_replace($pattern, $replace, $channel_ori));
            }
        } else {
            // 普通映射，可能为多对一
            $channels = array_map('trim', explode(',', $search));
            foreach ($channels as $singleChannel) {
                if (strcasecmp($channel, str_replace($channel_replacements, '', $singleChannel)) === 0) {
                    return strtoupper($replace);
                }
            }
        }
    }

    // 默认不进行繁简转换
    if ($t2s) {
        $channel = t2s($channel);
    }
    return strtoupper($channel);
}
```
在 public.php 替换这个就好了，确实是大小写的问题。

**Comment by nange01** [comment]
可以了，这会没问题了

**Comment by nange01** [comment]
目前有个新问题，你看看这是我的列表和模板，咪咕列表匹配出来好多重复的
[Uploading 模板.txt…]()
[Uploading tv (1).m3u…]()

**Comment by taksssss** [comment]
现在只有CCTV跟CGTN放到精确匹配里面了，其他都是模糊匹配。
最多就是做一个选项，只进行精确匹配。

**Comment by nange01** [comment]
这样也可以，避免有些频道出现匹配多个重复直播地址的情况
