### ISSUE TITLE
EPG解析问题

### ISSUE THREAD

**Issue by StefanLuo** [taksssss/EPG-Server#39]
大佬，我这里有一份epg文件无法解析入库，麻烦看下
[tel-epg.zip](https://github.com/user-attachments/files/18122152/tel-epg.zip)

**Comment by taksssss** [comment]
这个问题修复了，今天晚点会推送。
这个源部分频道数据丢失了，导致有个函数直接崩了。

**Comment by taksssss** [comment]
修复了

**Comment by StefanLuo** [comment]
> 修复了

谢谢大佬
