### ISSUE TITLE
有没有国内比较全的epg推荐？或者各位朋友可以介绍好用的全的epg

### ISSUE THREAD

**Issue by hecarli555** [taksssss/EPG-Server#40]
有没有国内比较全的epg推荐？或者各位朋友可以介绍好用的全的epg

**Comment by taksssss** [comment]
`https://github.com/taksssss/tv`
我自己觉得这几个加起来，还算比较全的。

**Comment by hecarli555** [comment]
> https://github.com/taksssss/tv 我自己觉得这几个加起来，还算比较全的。

CHC影迷电影，这个频道很少有，，，找了很多地方都没找到

**Comment by taksssss** [comment]
> > https://github.com/taksssss/tv 我自己觉得这几个加起来，还算比较全的。
> 
> CHC影迷电影，这个频道很少有，，，找了很多地方都没找到

这种比较小众的，官网也有数据，比较适合自己写代码做解析。

**Comment by taksssss** [comment]
不对，我看erw跟112114都有这个频道的信息啊。还有 https://epg.deny.vip/sh/tel-epg.xml 这个也有。

**Comment by hecarli555** [comment]
> 不对，我看erw跟112114都有这个频道的信息啊。还有 https://epg.deny.vip/sh/tel-epg.xml 这个也有。

卧槽。。。原来凌晨查不到是因为没更新。。。这些有了，感谢感谢
