### ISSUE TITLE
大佬，直播源管理有没有办法把会变化的m3u地址代理成固定的地址？

### ISSUE THREAD

**Issue by philboycn** [taksssss/EPG-Server#41]
大佬的epgserver超好用啊！直播源管理里面，能否把直播源地址转换成类似：

http://domain/?token=xxx&live=m3u/txt&tvg-id=xxx（频道号）
http://domain/?token=xxx&live=m3u/txt&tvg-name=xxx（频道名）

然后能设置定时刷新m3u源，实现源地址虽然有变化但转换出来的地址能固定的啊？

**Comment by taksssss** [comment]
没看懂想实现什么功能。&tvg-id=xxx的意思是只包含某个频道么？
源地址虽然有变化但转换出来的地址能固定又是什么意思？举个例子。

**Comment by philboycn** [comment]
> 没看懂想实现什么功能。&tvg-id=xxx的意思是只包含某个频道么？ 源地址虽然有变化但转换出来的地址能固定又是什么意思？举个例子。

对的，只包含某个频道。

我有一个python抓取的m3u源，每4个小时会自动刷新一次生成新的m3u文件，其中的#EXTINF这一行，tvg-id和tvg-name这些都不会变化，但是http源地址这一行会变化。

比如：
#EXTINF:0 tvg-name="美国BBC World News HD" tvg-id="1007" group-title="美国频道",美国BBC World News HD
http://domain/stream/3a1f25e2530b3c12446daab36462814a
4个小时后会变成：
#EXTINF:0 tvg-name="美国BBC World News HD" tvg-id="1007" group-title="美国频道",美国BBC World News HD
http://domain/stream/bcba93e4acd018e6662e9edaf94c090e


所以希望通过epgserver直播源管理的转换功能，把每4个小时变一次的源地址转换成固定的地址。

变成：
http://domain/?token=xxx&live=m3u/txt&tvg-id=1007
或者：
http://domain/?token=xxx&live=m3u/txt&tvg-name=%E7%BE%8E%E5%9B%BDBBC%20World%20News%20HD

**Comment by taksssss** [comment]
只要m3u地址不变，直播源地址更变，重新解析是会获取新地址的。
至于你说的按照频道名来生成，现在可以通过设置模板来实现，具体看页面底部的使用说明。

**Comment by philboycn** [comment]
> 只要m3u地址不变，直播源地址更变，重新解析是会获取新地址的。 至于你说的按照频道名来生成，现在可以通过设置模板来实现，具体看页面底部的使用说明。

好的，感谢大佬！
